name: 'Install Phoesion Glow Reactor Debugger'
description: 'Install Phoesion Glow Reactor Debugger tool'
inputs:
  repo:
    description: 'Repository source'
    required: false
    default: 'phoesion.glow'
  version:
    description: 'Version of package to install'
    required: true
runs:
  using: "composite"
  steps:
    - run: sudo ${{ github.action_path }}/install.sh "${{ inputs.repo }}" "${{ inputs.version }}"
      shell: bash
