name: 'Install Phoesion Glow Reactor Debugger'
description: 'Install Phoesion Glow Reactor Debugger tool'
inputs:
  repo:
    description: 'Repository source'
    required: false
    default: 'phoesion.glow'
  version:
    description: 'Version of package to install'
    required: true
  shell_cmd:
    description: 'Use speficied command to run installer script (can use `sudo` here if needed)'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - run: ${{ inputs.shell_cmd }} ${{ github.action_path }}/install.sh "${{ inputs.repo }}" "${{ inputs.version }}"
      shell: bash
